language: java
sudo: false
notifications:
  slack:
    secure: IewB2JuslmbngTGDBoxDOa+myPGCOYwmMTFXFCpE7i2xRiPNqkoAGUa6bbcoFVR5PF0Ukz6SVye3ITqLVGo3Sv9yWtbyauajyd+ZO9X+cp+h1Vv3X4SMzr8nx6mfC4/Uym2QQJOEroF5djP1RduNEjOBDjxx6reV/BowwgKNYkU=
deploy:
  provider: releases
  api_key:
    secure: dOR1qtgrZag95Ah3wbTgs1KZmBKb6RZx/qmnqbqB5gVsMLfssaVX3wYjoyKdi/WA6gHEZUnh6vWlF9O0xNJHukW5EACkWauYDNXTLv+6ZggkQrrvf27a2UfF9p2GDbptFXgYTsKsD/zYccXxRxP1C+ciEsr0tZ6dMnRfUs03ACM=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-xldeploy-plugin
